services:
  frigate-media-backup:
    image: ghcr.io/mattjgalloway/frigate-media-backup:latest
    restart: unless-stopped
    environment:
      B2_KEY_ID: "${B2_KEY_ID:-}"
      B2_APP_KEY: "${B2_APP_KEY:-}"
    volumes:
      - ../config/config.yaml:/config/config.yaml:ro
      - ../secrets:/run/secrets:ro
      - ../state:/state
      - ../backup:/backup
